#! /bin/fish

set -l currentDir $(dirname (status --current-filename))
set -l generatedFilePath $currentDir/conf.d/__fci_plugin_kubectl_fzf_auto_generated.fish

function kubectlGlobalOptions
    set options $(kubectl options | grep '^\s*-' | cut -d ':' -f 1 )

    set -l outputs
    for option in $options
        set splits (string split "," $option)
        set -l shortOption
        set -l longOption
        if [ "$splits[2]" != "" ]
            set shortOption (string trim (string replace -r '^\s*-' '' $splits[1]))
            set longOption $splits[2]
        else
            set longOption $splits[1]
        end

        set longOptions (string split "=" "$longOption")
        set longOptionName (string trim (string replace -r '^\s*--' '' $longOptions[1]))
        set optionValue $longOptions[2]

        set -l output
        if [ "$shortOption" != "" ]
            set output $output "$shortOption/"
        end
        set output $output "$longOptionName="
        if [ "$optionValue" = "false" ]; or [ "$optionValue" = "true" ]
            set output $output "?"
        end
        set outputs $outputs (string join "" $output)
    end

    set -l i 1
    set -l total_count (count $outputs)
    for row in $outputs
        echo -n "'"
        echo -n $row
        echo -n "'"
        if [ "$i" -lt "$total_count" ]
            echo -n " \\"
        end
        echo
        set i (math $i + 1)
    end
end

echo '# DO NOT EDIT THIS FILE.
# This file is automatically generated by a script.
' > $generatedFilePath
echo -n 'set -g __fci_plugin_kubectl_fzf_kubectl_global_options ' >> $generatedFilePath
kubectlGlobalOptions >> $generatedFilePath
